name: test path
on:
  push:
    branches:
      - feature-path

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install
      - run: npm run build

      - name: Create Tag
        id: create_tag
        uses: jaywcjlove/create-tag-action@main
        with:
          package-path: ./package.json

      - name: Generate Changelog (path test)
        id: changelog
        # uses: jaywcjlove/changelog-generator@main
        uses: ./
        with:
          path: ./.github/workflows/changelog.yml
          token: ${{ secrets.GITHUB_TOKEN }}
          head-ref: ${{steps.create_tag.outputs.version}}
          original-markdown: true
          filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

      - run: echo "outputs.tag - ${{ steps.changelog.outputs.tag }}"
      - run: echo "outputs.branch - ${{ steps.changelog.outputs.branch }}"
      - run: echo "outputs.compareurl - ${{ steps.changelog.outputs.compareurl }}"
      - run: echo "outputs.version - ${{ steps.changelog.outputs.version }}"
      - run: echo "outputs.gh-pages-hash - ${{ steps.changelog.outputs.gh-pages-hash }}"
      - run: echo "outputs.gh-pages-hash - ${{ steps.changelog.outputs['gh-pages-hash'] }}"
      - run: echo "outputs.gh-pages-short-hash - ${{ steps.changelog.outputs.gh-pages-short-hash }}"

      - name: Generate Changelog (folder path test)
        # uses: jaywcjlove/changelog-generator@main
        uses: ./
        with:
          path: ./.github/workflows/
          token: ${{ secrets.GITHUB_TOKEN }}
          head-ref: ${{steps.create_tag.outputs.version}}
          original-markdown: true
          filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

      - name: Generate Changelog (no "path:" test)
        # uses: jaywcjlove/changelog-generator@main
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          head-ref: ${{steps.create_tag.outputs.version}}
          original-markdown: true
          filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

